# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_utc_now_ea7cdc5c6f
ROOST_METHOD_SIG_HASH=get_utc_now_0129a168d0


```
Scenario 1: Validate whether the function get_utc_now returns the current date and time.
Details:
  TestName: test_get_utc_now_time
  Description: This test is meant to check if the function "get_utc_now" returns the current UTC date and time.
Execution:
  Arrange: There's no setup required as there are no additional parameters or environmental details.
  Act: Invoke the function "get_utc_now" and get a timestamp.
  Assert: Check if the generated timestamp is close to the present time.
Validation:
  Rationale: This function's purpose is to generate the 'current' timestamp. If the timestamp is too far from the present moment when the test is run, it implies something went wrong.

Scenario 2: Validate the timezone of the function get_utc_now.
Details:
  TestName: test_get_utc_now_timezone
  Description: This test is supposed to validate if the timezone associated with the datetime object returned by get_utc_now is UTC timezone.
Execution:
  Arrange: No setup required as the function take no arguments.
  Act: Invoke the function get_utc_now and inspect the tzinfo property of the returned datetime object.
  Assert: Ensure that the tzinfo is timezone.utc.
Validation:
  Rationale: The function is expected to give a timestamp in UTC. By checking the timezone of the timestamp given by the function, we can validate whether this especificity of the function is being upheld.

Scenario 3: Validate the type of the returned object of function get_utc_now
Details:
  TestName: test_get_utc_now_return_type
  Description: This test is intended to check whether the return type of the function "get_utc_now" is datetime.
Execution:
  Arrange: No setup is required as function doesn't take parameters.
  Act: Invoke the "get_utc_now" function and inspect the type of the returned object.
  Assert: Assert that the type of the return value is datetime.
Validation:
  Rationale: The function get_utc_now supposed to return a datetime object representing current time in UTC, and this test verifies if it is indeed returning a datetime object.   
```
"""

# ********RoostGPT********
import pytest
from datetime import datetime, timezone

from source_module import get_utc_now   # replace "source_module" with the actual module name


class Test_DatetimeGetUtcNow:
    @pytest.mark.parametrize('current_time', [datetime.now(tz=timezone.utc)])
    def test_get_utc_now_time(self, current_time):
        return_stamp = get_utc_now()
        assert abs((return_stamp - current_time).total_seconds()) <= 1, "The timestamp is not close to the current time"

    def test_get_utc_now_timezone(self):
        return_stamp = get_utc_now()
        assert return_stamp.tzinfo == timezone.utc, "The timezone is not UTC"
    
    def test_get_utc_now_return_type(self):
        return_value = get_utc_now()
        assert isinstance(return_value, datetime), "The return type is not datetime"
