# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___51fac2ff1b
ROOST_METHOD_SIG_HASH=__init___992df703dc


Scenario 1: Ensure Proper Initialization and Exception Message
Details:
  TestName: test_init_correct_message
  Description: This test verifies that the __init__ method correctly combines the input 'key' and 'error' into the exception message.
Execution: 
  Arrange: Initialize 'key' and 'error' variables with the desired test values. 
  Act: Invoke the __init__ method with the established parameters.
  Assert: Verify that the constructed exception message matches the expected result, consisting of the 'key' followed by ': ' and then the 'error'.
Validation:
  This test is key to ensuring that the exception message is consistent and informative, accurately reflecting both the cause of the error and the relevant key.

Scenario 2: Asserting Attributes' Assignment 
Details:
  TestName: test_init_attribute_assignment
  Description: This test verifies that the __init__ method correctly assigns the 'key' and 'error' parameters to the respective instance attributes.
Execution: 
  Arrange: Initialize 'key' and 'error' variables with the desired test values.
  Act: Invoke the __init__ method with the established parameters.
  Assert: Ensure the 'key' and 'error' attributes of the created object equate to their corresponding initialized values.
Validation:
  Ensuring correct attribute assignment is important as it certainty that the initialization process works as intended, enabling proper exception handling later.

Scenario 3: Test With Custom Exception Type
Details:
  TestName: test_init_custom_exception_type
  Description: This test aims to verify the function's behavior when the 'error' parameter is an instance of a custom Exception subclass instead of a string.
Execution: 
  Arrange: Formulate a custom Exception subclass. Initialize 'key' with a desired test value and 'error' as an instance of the custom exception.
  Act: Invoke the __init__ method with the established parameters.
  Assert: Check that the composed exception message holds the 'key', followed by ': ', and then the message of the custom exception.
Validation: 
  This test is essential to handle varied error types, enabling usage of more descriptive exception classes rather than simple strings. This extends error handling flexibility which is necessary in complex applications.
"""

# ********RoostGPT********
import pytest
from config import ConfigurationError

class Test_ConfigurationErrorInit:

    def test_init_correct_message(self):
        key = "testKey"
        error = "Test Error"
        exception = ConfigurationError(key, error)

        expected_message = f"{key}: {error}"
        assert str(exception) == expected_message

    def test_init_attribute_assignment(self):
        key = "testKey"
        error = "Test Error"
        exception = ConfigurationError(key, error)

        assert exception.key == key
        assert exception.error == error

    def test_init_custom_exception_type(self):
        class CustomException(Exception):
            pass

        key = "testKey"
        custom_error = CustomException("This is a custom exception")
        exception = ConfigurationError(key, custom_error)

        expected_message = f"{key}: {str(custom_error)}"
        assert str(exception) == expected_message        
