# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___a423f9dcec
ROOST_METHOD_SIG_HASH=__init___5a3c3d6a08


```
Scenario 1: Test initialization with size less than the MAX_EVENT_SIZE
Details:
  TestName: test_init_with_valid_size
  Description: This test is intended to verify that the __init__ function initializes successfully when the size passed in parameters is less than the MAX_EVENT_SIZE.
Execution:
  Arrange: No specific arrangement required as this is initiation with a parameter.
  Act: Call the `__init__` function with a size value of 50000.
  Assert: Check if the magnitude of the event size set in the `__init__` function is the same as the input value.
Validation:
  Rationalize: This test is important to ensure that the `__init__` function correctly sets the size of the event when it is within the acceptable range (ie. less than MAX_EVENT_SIZE).

Scenario 2: Test initialization with size equal to the MAX_EVENT_SIZE
Details:
  TestName: test_init_with_max_size
  Description: This test is intended to validate that the `__init__` function initializes successfully when the size passed is equal to the MAX_EVENT_SIZE.
Execution:
  Arrange: No specific arrangement required as this is initiation with a parameter.
  Act: Call the `__init__` function with a size value equal to MAX_EVENT_SIZE (102400).
  Assert: Check if the event size set in the `__init__` function is the same as the input value.
Validation:
  Rationalize: This scenario is necessary to confirm if the `__init__` function allows events that are precisely equal to MAX_EVENT_SIZE.

Scenario 3: Test initialization with size greater than the MAX_EVENT_SIZE
Details:
  TestName: test_init_with_over_max_size
  Description: This scenario is aimed at verifying whether the `__init__` function throws an exception when we try to initialize with a size greater than the MAX_EVENT_SIZE.
Execution:
  Arrange: No specific arrangement required as this is initiation with a parameter.
  Act: Call the `__init__` function with a size value greater than the MAX_EVENT_SIZE (e.g., 102401).
  Assert: Confirm that the `__init__` function throws an error stating "Event is too large to send".
Validation:
  Rationalize: It's crucial to verify the function's behavior when given a value exceeding the maximum limit to ensure that event sizes beyond the system's capacity are not entertained.
```
"""

# ********RoostGPT********
# Necessary imports
import pytest
from events import EventTooLargeError

MAX_EVENT_SIZE = 102400

class Test_EventTooLargeErrorInit:
    @pytest.mark.positive
    def test_init_with_valid_size(self):
        # Act
        error = EventTooLargeError(50000)
        # Assert
        assert "50000" in str(error)

    @pytest.mark.positive
    def test_init_with_max_size(self):
        # Act
        error = EventTooLargeError(MAX_EVENT_SIZE)
        # Assert
        assert str(MAX_EVENT_SIZE) in str(error)

    @pytest.mark.negative
    def test_init_with_over_max_size(self):
        # Act
        with pytest.raises(EventTooLargeError) as e_info:
            error = EventTooLargeError(MAX_EVENT_SIZE + 1)
        # Assert
        assert "Event is too large to send" in str(e_info.value)
