# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Percent_9b7a3a2bb7
ROOST_METHOD_SIG_HASH=Percent_5879c033c9


```
Scenario 1: Valid Percentage Input
Details:
  TestName: test_valid_percentage_input
  Description: The test is intended to verify that the function correctly parses and convert valid string representation of percentage to a float in the range [0.0, 1.0].
Execution:
  Arrange: No specific setup or environment preparation is required for this scenario
  Act: Invoke the function Percent with a valid string percentage like "25%".
  Assert: Check if the function returns the correct float representation of the percentage (in this case 0.25).
Validation:
  It is crucial to ensure that the function correctly handles valid input as per the business requirements. This ensures the function's basic functionality.

Scenario 2: Input without Percentage Symbol
Details:
  TestName: test_without_percentage_symbol
  Description: This test will verify that the function raises a ValueError when the input doesn't end with a '%' symbol.
Execution:
  Arrange: No specific setup or environment preparation is required.
  Act: Invoke the function Percent with string input that does not end with '%' ("42").
  Assert: Check if ValueError is being raised.
Validation:
  This test is critical as the function should prevent erroneous data from being processed. It validates the expectation that the text must be a percentage.

Scenario 3: Percentage Out of  Range
Details:
  TestName: test_percentage_out_of_range
  Description: This is geared towards verifying that the function raises a ValueError when the input percentage is outside the valid range [0, 100].
Execution:
  Arrange: No specific setup or environment preparation is required.
  Act: Invoke the Percent function with a string percentage that's outside the valid range like "105%".
  Assert: Check that a ValueError is raised.
Validation:
  This test is crucial since it is stated in the function's expectations that percentages should be in the range of 0-100%. The business requirements clearly state this as necessary and hence it is important to ensure this is enforced.

Scenario 4: Negative Percentage Input
Details:
  TestName: test_negative_percentage_input
  Description: This test will establish that the function raises a ValueError when the input percentage is negative.
Execution:
  Arrange: No specific setup or environment preparation is required.
  Act: Invoke the function Percent with a negative string percentage like "-10%".
  Assert: Check that a ValueError is raised.
Validation:
  This is an important test as it asserts the function's ability to handle incorrect data properly. The function is expected to reject any negative percentages as they fall outside the valid range of 0-100%.
```
"""

# ********RoostGPT********
import pytest
from config import Percent

class Test_ConfigPercent:
    @pytest.mark.positive
    def test_valid_percentage_input(self):
        assert Percent("25%") == 0.25

    @pytest.mark.negative
    def test_without_percentage_symbol(self):
        with pytest.raises(ValueError):
            Percent("42")

    @pytest.mark.negative
    def test_percentage_out_of_range(self):
        with pytest.raises(ValueError):
            Percent("105%")

    @pytest.mark.negative
    def test_negative_percentage_input(self):
        with pytest.raises(ValueError):
            Percent("-10%")
