# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Endpoint_f8c5d6acde
ROOST_METHOD_SIG_HASH=Endpoint_e010b9764b


```
Scenario 1: Test with Empty Text Input
Details:
  TestName: test_empty_text_input
  Description: The test is intended to verify that the Endpoint function throws an exception when no endpoint is provided. 
Execution:
  Arrange: No arrange needed as we are not passing any input.
  Act: Call the Endpoint function with an empty string.
  Assert: A ValueError with the message "no endpoint specified" should be raised.
Validation:
  The function specifies that it should throw an error when no endpoint is provided. This test case is crucial to ensure input validation for the Endpoint function.

Scenario 2: Test with String containing Slash
Details:
  TestName: test_string_with_slash
  Description: This will test whether the Endpoint function correctly interprets a string with a slash as a UNIX domain socket path.
Execution:
  Arrange: Provide input text as a path string containing a slash.
  Act: Call the Endpoint function with the path string.
  Assert: The function should return an EndpointConfiguration with socket.AF_UNIX as family and the path string as address.
Validation:
  The functionality is designed to distinguish between host:port pair and a UNIX domain, verifying this is important to ensure the correct endpoint is targeted.

Scenario 3: Test with Invalid Endpoint String
Details:
  TestName: test_invalid_endpoint
  Description: The test is intended to verify that the function throws an exception when the endpoint string does not contain a port.
Execution:
  Arrange: Provide an endpoint string without a port.
  Act: Call the function with the endpoint string.
  Assert: A ValueError with the message "no port specified" should be raised.
Validation:
  The function specifies that it should throw an error if an endpoint string does not contain a port. This test case is crucial for maintaining communication pipelines.

Scenario 4: Test with Valid Endpoint String
Details:
  TestName: test_valid_endpoint
  Description: This will test whether the Endpoint function correctly interprets a valid endpoint string and returns an appropriate EndpointConfiguration.
Execution:
  Arrange: Provide a valid endpoint string with host and port.
  Act: Call the function with the endpoint string.
  Assert: The function should return an EndpointConfiguration with socket.AF_INET as family and a tuple of host and port as address.
Validation:
  This is important as it tests the normal behaviour of the function as per specifications, ensuring correct interpretation and communication with correct endpoint.
```
"""

# ********RoostGPT********
import pytest
import socket
from config import Endpoint, EndpointConfiguration
from typing import Tuple

class Test_ConfigEndpoint:

    @pytest.mark.negative
    def test_empty_text_input(self):
        with pytest.raises(ValueError, match="no endpoint specified"):
            Endpoint('')

    @pytest.mark.regression
    def test_string_with_slash(self):
        input_val = 'path/to/socket'
        result = Endpoint(input_val)
        assert isinstance(result, EndpointConfiguration)
        assert result.family == socket.AF_UNIX
        assert result.address == input_val

    @pytest.mark.negative
    def test_invalid_endpoint(self):
        with pytest.raises(ValueError, match="no port specified"):
            Endpoint('127.0.0.1')

    @pytest.mark.regression
    def test_valid_endpoint(self):
        input_val = '127.0.0.1:8080'
        result = Endpoint(input_val)
        assert isinstance(result, EndpointConfiguration)
        assert result.family == socket.AF_INET
        assert result.address == ('127.0.0.1', 8080)
