# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=parse_config_3781877341
ROOST_METHOD_SIG_HASH=parse_config_e538ad2151


```
Scenario 1: Valid Configuration against Perfect Spec
Details:
  TestName: test_parse_config_valid_config
  Description: This test verifies if parse_config can handle a valid configuration and spec.
Execution:
  Arrange: Create a valid `RawConfig` and `ConfigSpec` objects.
  Act: Invoke the function with these parameters.
  Assert: Check that the output matches the expected `ConfigNamespace`. There should be no `ConfigurationError` raised.
Validation:
  This test is important to ensure that the function works as expected under normal circumstances. The expected result is a `ConfigNamespace` with parsed configuration values.

Scenario 2: Invalid Configuration against Perfect Spec
Details:
  TestName: test_parse_config_invalid_config
  Description: This test is intended to verify how the function handles an invalid configuration against a perfect spec.
Execution:
  Arrange: Create an invalid `RawConfig` object and a valid `ConfigSpec` object.
  Act: Invoke the function with these parameters.
  Assert: Check that the function raises a `ConfigurationError`.
Validation:
  The function should raise errors when the configuration and the spec are incompatible. This helps us ensure that invalid configurations are detected and the appropriate error messages are raised. 

Scenario 3: Valid Configuration against Incorrect Spec
Details:
  TestName: test_parse_config_incorrect_spec
  Description: This test is intended to verify how the function handles a valid configuration against an incorrect spec.
Execution:
  Arrange: Create a valid `RawConfig` object and an invalid `ConfigSpec` object.
  Act: Invoke the function with these parameters.
  Assert: Check that the function raises an appropriate error or returns an unexpected `ConfigNamespace`.
Validation:
  The function should detect incompatible specs and configurations to avoid misinterpretation of the configuration values.

Scenario 4: Parsing a configuration with nested structures
Details:
  TestName: test_parse_config_nested
  Description: This test is intended to verify how the parse_config function handles configurations and specs with nested structures.
Execution:
  Arrange: Create a `RawConfig` and `ConfigSpec` objects with nested structures.
  Act: Invoke the function with these parameters.
  Assert: Check that the output matches the expected `ConfigNamespace` with correctly parsed nested structures.
Validation:
  This test is important because it ensures that the function can handle more complex configuration/spec structures accurately.
```

"""

# ********RoostGPT********
import pytest
from config import parse_config, ConfigurationError, ConfigNamespace, RawConfig, ConfigSpec

class Test_ConfigParseConfig:
    def test_parse_config_valid_config(self):
        raw_config = {'key1': 'value1', 'key2': 'value2'}  # valid config
        config_spec = {'key1': str, 'key2': str}  # perfect spec
        expected_namespace = ConfigNamespace(key1='value1', key2='value2')
        parsed_config = parse_config(raw_config, config_spec)
        assert parsed_config == expected_namespace 

    def test_parse_config_invalid_config(self):
        raw_config = {'key1': 'value1', 'key3': 'value3'}  # invalid config
        config_spec = {'key1': str, 'key2': str}  # perfect spec
        with pytest.raises(ConfigurationError):
            parse_config(raw_config, config_spec)

    def test_parse_config_incorrect_spec(self): 
        raw_config = {'key1': 'value1', 'key2': 'value2'}  # valid config
        config_spec = {'key1': str, 'key3': str}  # incorrect spec
        with pytest.raises(ConfigurationError):
            parse_config(raw_config, config_spec)

    def test_parse_config_nested(self):
        raw_config = {'key1': 'value1', 'key2': {'nested_key': 'nested_value'}}  # config with nested structure
        config_spec = {'key1': str, 'key2': {'nested_key': str}}  # spec with nested structure
        expected_namespace = ConfigNamespace(key1='value1', key2=ConfigNamespace(nested_key='nested_value'))
        parsed_config = parse_config(raw_config, config_spec)
        assert parsed_config == expected_namespace
