# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Percent_9b7a3a2bb7
ROOST_METHOD_SIG_HASH=Percent_5879c033c9


Scenario 1: Successful Conversion of Percentage String to Float
Details:
  TestName: test_successful_conversion
  Description: This test verifies the function's primary business logic, where a valid percentage string is converted into a float in the range of [0.0, 1.0].
Execution:
  Arrange: No arrangement is necessary outside of defining a valid percentage string. An instance of the string could be "50%".
  Act: The function will be invoked with the defined string as a parameter.
  Assert: Assert that the output is equivalent to the float representation of the percentage, like 0.5 in this case.
Validation:
  This test validates the main functionality of the Percent() function. Given correct input, the function should work per specification and return the expected result.

Scenario 2: Invalid Percentage String without Percent Symbol
Details:
  TestName: test_missing_percentage_symbol
  Description: This test checks whether the function will correctly raise a ValueError when the input string does not end with a percentage symbol.
Execution:
  Arrange: Define an invalid percentage string that does not end with '%'. For instance, the string could be "30.5".
  Act: Invoke the function with the invalid percentage string.
  Assert: Assert that a ValueError is raised with the specific error message "the value is not a percentage".
Validation:
  This test ensures that the function enforces its requirement for input to end with a percentage symbol, thereby guarding against erroneous input.

Scenario 3: Percentage Value Out of Acceptable 0 to 100 Range
Details:
  TestName: test_out_of_range_percentage
  Description: This test checks if the function correctly raises a ValueError when the numerical value of the percentage is not in the range [0, 100].
Execution:
  Arrange: An instance of an invalid percentage string with a numerical value outside the acceptable range, such as "105%".
  Act: Invoke the function using the invalid percentage string.
  Assert: Assert that ValueError is raised with the error message "percentage is out of valid range".
Validation:
  This test ensures that the function correctly identifies and handles percentage values outside of the acceptable range, preventing errors in further computations. 

Scenario 4: Valid Percentage String with No Fractional Value
Details:
  TestName: test_percentage_without_fractional_value
  Description: This test examines the function's ability to handle percentage strings that have no fractional component.
Execution:
  Arrange: Set up a valid percentage string without a fractional component, such as "80%".
  Act: The function will be invoked with this valid percentage string.
  Assert: Verify that the correct corresponding float is returned by the function, in this case, 0.8.
Validation:
  This test validates that the function can handle varied valid inputs correctly, supporting its robustness and versatility.
"""

# ********RoostGPT********
import pytest
from config import Percent

class Test_ConfigPercent:

    # Scenario 1: Successful Conversion of Percentage String to Float
    def test_successful_conversion(self):
        input_string = "50%"
        assert Percent(input_string) == 0.5
    
    # Scenario 2: Invalid Percentage String without Percent Symbol
    def test_missing_percentage_symbol(self):
        input_string = "30.5"
        with pytest.raises(ValueError, match="the value is not a percentage"):
            Percent(input_string)
    
    # Scenario 3: Percentage Value Out of Acceptable 0 to 100 Range
    def test_out_of_range_percentage(self):
        input_string = "105%"
        with pytest.raises(ValueError, match="percentage is out of valid range"):
            Percent(input_string)

    # Scenario 4: Valid Percentage String with No Fractional Value
    def test_percentage_without_fractional_value(self):
        input_string = "80%"
        assert Percent(input_string) == 0.8
