# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Optional_7f83e24633
ROOST_METHOD_SIG_HASH=Optional_041c4c0dca


```
Scenario 1: Testing the Optional function when a non-empty string is passed
Details:
  TestName: testOptional_withNonEmptyString
  Description: This test verifies that when a non-empty string is parsed, the function will not default to the default value. It should call the parser function with the provided string value and return the parsed result.
Execution:
  Arrange: Initialize a parser function and a default value for the test.
  Act: Invoke the Optional function with the parser function, default value, and a non-empty string as input.
  Assert: The result of the function should be the same as the output of the parser function invoked with the non-empty string.
Validation:
  This test is important to ensure that the function correctly applies the parser function to the non-empty input string. It matches the business requirement where the function is expected to parse the input text if it's not an empty string.

Scenario 2: Testing the Optional function when an empty string is passed
Details:
  TestName: testOptional_withEmptyString
  Description: This test verifies that when an empty string is parsed, the function will return the default value.
Execution:
  Arrange: Initialize a parser function and a default value for the test.
  Act: Invoke the Optional function with the parser function, default value, and an empty string as input.
  Assert: The result of the function should be the default value.
Validation:
  This test ensures that the function correctly returns the default value when an empty string is passed. It aligns with the business requirement where the function is supposed to return the default value if the input text is not configured (i.e., is empty).

Scenario 3: Testing the exception case when the parser function throws an error
Details:
  TestName: testOptional_withExceptionInParser
  Description: This test checks whether the function throws an exception when the parser function does so.
Execution:
  Arrange: Initialize a parser function that throws an exception and a default value for the test.
  Act: Invoke the Optional function with the exception-throwing parser function, a default value, and a non-empty string as input.
  Assert: An exception should be thrown from the Optional function.
Validation:
  This test confirms the function correctly propagates exceptions thrown by the parser function. Ensuring correct exception handling is an integral part of maintaining a stable software system.
```
"""

# ********RoostGPT********
import pytest
from config import Optional

class Test_ConfigOptional:

    # Scenario 1: Testing the Optional function when a non-empty string is passed
    def testOptional_withNonEmptyString(self):
        parser_function = int
        default_value = 0
        input_string = "123"

        # Act: Invoke the Optional function
        optional_func = Optional(parser_function, default_value)
        result = optional_func(input_string)

        # Assert: The result of the function should be the same as the output of the parser function
        assert result == parser_function(input_string)

    # Scenario 2: Testing the Optional function when an empty string is passed
    def testOptional_withEmptyString(self):
        parser_function = int
        default_value = 0
        input_string = ""

        # Act: Invoke the Optional function
        optional_func = Optional(parser_function, default_value)
        result = optional_func(input_string)

        # Assert: The result of the function should be the default value
        assert result == default_value

    # Scenario 3: Testing the exception case when the parser function throws an error
    def testOptional_withExceptionInParser(self):
        def exception_throwing_parser(text: str):
            raise ValueError("Parser error")

        default_value = 0
        input_string = "invalid_integer"

        # Act: Invoke the Optional function with the exception-throwing parser function
        optional_func = Optional(exception_throwing_parser, default_value)
        
        # Assert: An error should be thrown from the Optional function.
        with pytest.raises(ValueError, match="Parser error"):
            optional_func(input_string)
