# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___8c554758b1
ROOST_METHOD_SIG_HASH=__init___abb95599e7


Scenario 1: Testing callable assignment
Details:
  TestName: test_callable_assignment
  Description: This test is intended to verify whether correct callable object is assigned when instance of the class is created.
Execution:
  Arrange: Initialize a callable object (any user-defined function or lambda function).
  Act: Create an instance of the class with the callable object.
  Assert: Check the equality of this instance callable and the originally initiated callable.
Validation:
  The callable field is a crucial attribute for the class object as its execution is likely to be critical to other program methods. Hence, it's essential to ensure that callable is assigned without any errors.


Scenario 2: Testing exception handling with key error construct
Details:
    TestName: test_key_error_constructor
    Description: This test is to verify if the correct key error is thrown when exception is raised.
Execution:
    Arrange: Initialize a key, and an error (it can be a string or an exception).
    Act: Create an instance of the class by passing key and error.
    Assert: Check if the instance error and instance key matches with the initially assigned error and key.
Validation:
    Key error construct is typically used to display more explicit and customized error messages to users, the correct output of the key and error greatly helps debugging.


Scenario 3: Testing config specification assignment
Details:
  TestName: test_config_spec_assignment
  Description: This test ensures that the ConfigSpec object is correctly assigned when the instance is being created.
Execution:
  Arrange: Initialize a ConfigSpec object.
  Act: Create an instance of the class with the ConfigSpec object.
  Assert: Check the equality of the instance spec and the previously initiated ConfigSpec.
Validation:
  ConfigSpec is an important parameter, since it is likely to hold important configuration data for the application. Ensuring its correct assignment during instantiation supports the overall execution of business logic.


Scenario 4: Testing default constructor
Details:
  TestName: test_default_constructor
  Description: This test intended to check if by default, the instance gives the dictionary of its own attributes.
Execution:
  Arrange: No arrangement needed as testing is for default instantiation.
  Act: Create an instance of the class without passing any arguments.
  Assert: Check if the dictionary of the object equals the object itself.
Validation:
  The default constructor appears to be designed to provide a type of reflection. Making sure this functions as desired is crucial to avoid errors when observing object state.
"""

# ********RoostGPT********
import pytest
from typing import Callable, TypeVar
from config import CallableParser

T = TypeVar('T')

class Test_CallableParserInit:

    def test_callable_assignment(self):
        callable_object = lambda x: x ** 2
        instance = CallableParser(callable_object)
        assert instance.callable == callable_object

    def test_key_error_constructor(self):
        key = 'test_key'
        error = 'Key Error'
        instance = CallableParser.KeyedError(key, error)
        assert instance.key == key
        assert instance.error == error

    def test_config_spec_assignment(self):
        ConfigSpec = dict[str, Callable[[str], T]]
        spec = ConfigSpec({'a': lambda a: a*2})
        instance = CallableParser(spec)
        assert instance.spec == spec

    def test_default_constructor(self):
        instance = CallableParser()
        assert vars(instance) == instance.__dict__
