# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Percent_9b7a3a2bb7
ROOST_METHOD_SIG_HASH=Percent_5879c033c9


```
Scenario 1: Valid percentage as a whole number
Details:
  TestName: test_valid_percentage_as_whole_number
  Description: This test verifies that when a valid percentage in the form of a whole number is passed to the function, it produces the expected output.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "50%".
  Assert: The function should return 0.50 (float) as the output.
Validation:
  Rationalize: This test scenario is important because it involves a typical situation where valid percentage text value is passed to the function and ensures function handles whole number percentages correctly.

Scenario 2: Valid percentage as a decimal number
Details:
  TestName: test_valid_percentage_as_decimal_number
  Description: This test verifies that when a valid percentage in the form of a decimal number is passed to the function, it produces the intended output.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "37.2%".
  Assert: The function should return 0.372 (float) as the output.
Validation:
  Rationalize: This test scenario checks the function's ability to handle decimal percentages correctly.

Scenario 3: Valid percentage as maximum boundary
Details:
  TestName: test_valid_percentage_as_max_boundary
  Description: This test verifies that the function handles the maximum valid boundary input (100%) appropriately.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "100%".
  Assert: The function should return 1.0 (float) as the output.
Validation:
  Rationalize: This test scenario is considered to validate correct boundary condition computations.

Scenario 4: Valid percentage as minimum boundary
Details:
  TestName: test_valid_percentage_as_min_boundary
  Description: This test verifies that the function handles the minimum valid boundary input (0%) appropriately.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "0%".
  Assert: The function should return 0.0 (float) as the output.
Validation:
  Rationalize: This test scenario is considered to validate correct boundary condition computations.

Scenario 5: Text ending with a character other than '%'
Details:
  TestName: test_input_without_percentage_symbol
  Description: This test verifies that the function throws an error when the input text does not end with '%' character.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "50".
  Assert: The function should throw "ValueError" with the message "the value is not a percentage".
Validation:
  Rationalize: This test scenario is needed to validate the function's robustness against incorrect input.

Scenario 6: Invalid percentage exceeding maximum boundary
Details:
  TestName: test_percentage_exceeding_max_boundary
  Description: This test verifies that the function throws an error when a percentage value exceeding the maximum boundary (100%) is passed.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "250%".
  Assert: The function should throw "ValueError" with the message "percentage is out of valid range".
Validation:
  Rationalize: This test scenario deals with an edge case where an out of bound value is input, and checks that the function correctly rejects such cases.

Scenario 7: Invalid percentage below minimum boundary
Details:
  TestName: test_percentage_below_min_boundary
  Description: This test verifies that the function throws an error when a percentage value below the minimum boundary (0%) is passed.
Execution:
  Arrange: There is no setup required for this scenario.
  Act: Call the Percent function with text = "-50%".
  Assert: The function should throw "ValueError" with the message "percentage is out of valid range".
Validation:
  Rationalize: This test scenario deals with an edge case where a negative value is input, and checks that the function correctly rejects such cases.
```
"""

# ********RoostGPT********
# Necessary imports
import pytest
# Import for the function/method to be tested
from config import Percent

class Test_ConfigPercent:
    @pytest.mark.valid
    def test_valid_percentage_as_whole_number(self):  # Scenario 1
        assert Percent("50%") == 0.50

    @pytest.mark.valid
    def test_valid_percentage_as_decimal_number(self):  # Scenario 2
        assert Percent("37.2%") == 0.372

    @pytest.mark.boundary
    def test_valid_percentage_as_max_boundary(self):  # Scenario 3
        assert Percent("100%") == 1.0

    @pytest.mark.boundary
    def test_valid_percentage_as_min_boundary(self):  # Scenario 4
        assert Percent("0%") == 0.0

    @pytest.mark.invalid
    def test_input_without_percentage_symbol(self):  # Scenario 5
        with pytest.raises(ValueError, match="the value is not a percentage"):
            Percent("50")

    @pytest.mark.invalid
    def test_percentage_exceeding_max_boundary(self):  # Scenario 6
        with pytest.raises(ValueError, match="percentage is out of valid range"):
            Percent("250%")

    @pytest.mark.invalid
    def test_percentage_below_min_boundary(self):  # Scenario 7
        with pytest.raises(ValueError, match="percentage is out of valid range"):
            Percent("-50%")
