# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___a423f9dcec
ROOST_METHOD_SIG_HASH=__init___5a3c3d6a08


```
Scenario 1: Validate Occurrence of the Exception on Event Exceeding Max Size
Details:
  TestName: test_should_throw_exception_when_event_size_exceeds_max_size
  Description: This test is intended to verify the exception triggered when the size of the event exceeds the MAX_EVENT_SIZE defined in the module-level assignments.
Execution:
  Arrange: Initialise an object instance size greater than MAX_EVENT_SIZE.
  Act: Call the __init__ function with the initialized size.
  Assert: Check if the appropriate exception is thrown.
Validation:
  This test is critical to ensure the exception is properly thrown when an event exceeds the maximum size limit. This keeps the system robust and avoids potential crashes due to oversized events.

Scenario 2: Validate Proper Initialization With Allowed Event Size
Details:
  TestName: test_init_succeeds_with_allowed_event_size
  Description: This test is intended to validate that the __init__ function successfully initializes objects with sizes less or equal to the MAX_EVENT_SIZE.
Execution:
  Arrange: Initialize an object with a size that is less than or equal to MAX_EVENT_SIZE.
  Act: Call the __init__ function with the initialized size.
  Assert: Check that the object is successfully initiated and no exception is thrown. 
Validation:
  This scenario validates that the __init__ function correctly initializes the object when called with valid event sizes. It helps in maintaining system integrity and in operating under normal limits.

Scenario 3: Validate Proper Error Message Display
Details:
  TestName: test_error_message_shows_proper_count_of_bytes
  Description: This test is intended to check whether the function displays an error message that precisely states the number of bytes that are too large to send.
Execution:
  Arrange: Initialize an object instance size greater than MAX_EVENT_SIZE.
  Act: Call the __init__ function with the initialized size.
  Assert: Check if the thrown exception contains a correct message detailing the number of bytes that were too large to send.
Validation:
  This test ensures that the function provides an error message that accurately shows the event size in bytes which was too large to send. This helps in debugging and offers insights on the size limitations enforced by the system.
```

"""

# ********RoostGPT********
# Importing Required Libraries
import pytest

# Importing Tested Functionality
from events import EventTooLargeError

# Test Class
class Test_EventTooLargeErrorInit:

    # Test Constants
    MAX_EVENT_SIZE = 102400

    # Scenario 1: Validate Occurrence of the Exception on Event Exceeding Max Size
    def test_should_throw_exception_when_event_size_exceeds_max_size(self):
        with pytest.raises(EventTooLargeError):
            size = self.MAX_EVENT_SIZE + 1 
            EventTooLargeError(size)
    
    # Scenario 2: Validate Proper Initialization With Allowed Event Size
    def test_init_succeeds_with_allowed_event_size(self):
        try: 
            size = self.MAX_EVENT_SIZE 
            EventTooLargeError(size)
        except EventTooLargeError:
            pytest.fail("EventTooLargeError was raised")

    
    # Scenario 3: Validate Proper Error Message Display
    def test_error_message_shows_proper_count_of_bytes(self):
        try: 
            size = self.MAX_EVENT_SIZE + 1
            with pytest.raises(EventTooLargeError) as excinfo:
                EventTooLargeError(size)
        except EventTooLargeError:
            assert str(excinfo.value) == f'Event is too large to send ({size:d} bytes)'
        else:
            pytest.fail("EventTooLargeError was not raised")
