# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBaseplateRepo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___a14fbc9b07
ROOST_METHOD_SIG_HASH=__init___b64b0ce934


```
Scenario 1: Test whether the logger is correctly initialized
Details:
  TestName: test_logger_initialized
  Description: The test verifies that a logger with the correct details is being initialized within the __init__ function.
Execution:
  Arrange: Initialization of the object would be arranged here.
  Act: The __init__ function will be invoked by creating a new instance of the associated class.
  Assert: The outcome to be checked is if the logger attribute of the object is of type 'logging.Logger' and whether it's name attribute matches '__name__'.
Validation:
  The test ensures that the logging system is correctly initialized for the class and guarantees the ability to log any error, debug, or critical information.

Scenario 2: Test if getLogger method from logging module is called while initializing logger
Details:
  TestName: test_getLogger_called
  Description: This test will ensure that initialization of logger involves a call to the getLogger method from the logging module.
Execution:
  Arrange: Mock the 'logging.getLogger' method before initializing the object.
  Act: The __init__ function will be invoked by creating a new instance of the associated object.
  Assert: Check if the 'getLogger' method was called once.
Validation:
  The test validates that the correct function 'getLogger' from the logging module is being employed to initialize the logger. This is necessary for the correct creation and functioning of the logger.

Scenario 3: Test logger with incorrect initialization detail
Details:
  TestName: test_incorrect_logger_initialization
  Description: This scenario tests the behavior if the logger is not initialized with '__name__'.
Execution:
  Arrange: Mock the 'logging.getLogger' method before initializing the object to return a logger initialized with an incorrect name.
  Act: The __init__ method is invoked by instantiating the associated object.
  Assert: Check if the name attribute of the logger is not '__name__'.
Validation:
  This test scenario ensures that the logger can be correctly identified and is specific to the scope of the class where it is initialized. This confirmation is required to ensure that logging information does not get incorrectly logged in a different logger due to a wrong logger name.
"""

# ********RoostGPT********
import logging
from unittest import TestCase
from unittest.mock import patch
from events import DebugLogger


class Test_DebugLoggerInit(TestCase):
    def setUp(self):
        self.debug_logger = DebugLogger()

    @patch('logging.getLogger')
    def test_logger_initialized(self, mock_getLogger):
        mock_getLogger.return_value = logging.getLogger(__name__)

        self.assertIsInstance(self.debug_logger.logger, logging.Logger)
        self.assertEqual(self.debug_logger.logger.name, __name__)

    @patch('logging.getLogger')
    def test_getLogger_called(self, mock_getLogger):
        self.debug_logger.__init__()

        mock_getLogger.assert_called_once_with(__name__)

    @patch('logging.getLogger')
    def test_incorrect_logger_initialization(self, mock_getLogger):
        incorrect_logger = logging.getLogger('incorrect_name')
        mock_getLogger.return_value = incorrect_logger

        self.assertNotEqual(self.debug_logger.logger.name, '__name__')
